project:
  type: website
  output-dir: docs

website:
  title: "Home"
  favicon: logo.png
  navbar:
    left:
      - href: research/index.qmd
        text: Investigación/Research
      - href: cv.pdf
        text: CV
      - href: Docencia.qmd
        text: Docencia/Teaching



format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor:
  render-on-save: true
